---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 7.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.18.3

    podAnnotations:
      secret.reloader.stakater.com/reload: "zigbee-mqtt-secrets"

    replicas: 1
    strategy:
      type: Recreate

    env:
      TZ: "Europe/Stockholm"
      ZIGBEE2MQTT_DATA: /data

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: "https://github.com/Koenkk/zigbee2mqtt/blob/dev/images/logo_vector.svg?raw=true"
        forecastle.stakater.com/network-restricted: "true"
      hosts:
        - host: zigbee.komhem.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "zigbee.komhem.xyz"

    securityContext:
      privileged: true

    persistence:
      data:
        enabled: true
        mountPath: /data
        skipuninstall: true
        existingClaim: "zigbee2mqtt-data"

    additionalVolumeMounts:
      - name: usb
        mountPath: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018DF4362-if00

    additionalVolumes:
      - name: usb
        hostPath:
          path: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018DF4362-if00

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - {key: "feature.node.kubernetes.io/usb-02_0451_16a8.present", operator: In, values: ["true"]}

    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"

    config:
      mqtt:
        server: mqtt://mosquitto
      frontend:
        port: 8080
      experimental:
        new_api: true

  valuesFrom:
    - kind: Secret
      name: "zigbee-mqtt-secrets"
      valuesKey: values.yaml
      optional: false
