---

skip_list:
  - yaml

exclude_paths:
  - ~/.ansible
  - .github/
  - .taskfiles/
  - bootstrap/
  - cluster/
  - docker/
  - docs/
  - tools/

warn_list:  # or 'skip_list' to silence them completely
  - command-instead-of-shell  # Use shell only when shell functionality is required
  - experimental  # all rules tagged as experimental
  - no-changed-when  # Commands should not change things if nothing needs doing
