---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 2.4.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:

    configInline:
      # The address-pools section lists the IP addresses that MetalLB is
      # allowed to allocate, along with settings for how to advertise
      # those addresses over BGP once assigned. You can have as many
      # address pools as you want.
      address-pools:
        - name: default
          # Protocol can be used to select how the announcement is done.
          # Supported values are bgp and layer2.
          protocol: layer2
          # A list of IP address ranges over which MetalLB has
          # authority. You can list multiple ranges in a single pool, they
          # will all share the same settings. Each range can be either a
          # CIDR prefix, or an explicit start-end range of IPs.
          addresses:
            - 192.168.20.201-192.168.20.250

    rbac:
      # create specifies whether to install and use RBAC rules.
      create: true

    # Prometheus Operator alertmanager alerts
    prometheusRule:
      enabled: true

    controller:
      image:
        registry: docker.io
        repository: metallb/controller
        tag: v0.10.1
        pullPolicy: IfNotPresent

      prometheus:
        enabled: false

        # Prometheus Operator service monitors
        serviceMonitor:
          # enable support for Prometheus Operator
          enabled: false
          # Job label for scrape target
          jobLabel: "app.kubernetes.io/name"
          # Scrape interval. If not set, the Prometheus default scrape interval is used.
          interval: ""
          metricRelabelings: []
          relabelings: []

      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          memory: 25Mi
          cpu: 25m

    speaker:
      image:
        registry: docker.io
        repository: metallb/speaker
        tag: v0.10.2
        pullPolicy: IfNotPresent

      prometheus:
        enabled: false

        # Prometheus Operator service monitors
        serviceMonitor:
          # enable support for Prometheus Operator
          enabled: false
          # Job label for scrape target
          jobLabel: "app.kubernetes.io/name"
          # Scrape interval. If not set, the Prometheus default scrape interval is used.
          interval: ""
          metricRelabelings: []
          relabelings: []

      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          memory: 25Mi
          cpu: 25m
