---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 3.27.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      ingressClass: internal
      replicaCount: 2
      extraEnvs:
        - name: TZ
          value: Europe/Stockholm
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.20.210
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        # Setting use-proxy-protocol to true will break the proxy
        use-proxy-protocol: "false"
        proxy-body-size: "0"
        use-forwarded-headers: "true"
      metrics:
        enabled: false
        serviceMonitor:
          enabled: true
          namespace: kube-system
      extraArgs:
        default-ssl-certificate: "kube-system/cert-komhem-wildcard"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - ingress-nginx-internal
              topologyKey: "kubernetes.io/hostname"
      resources:
        requests:
          memory: 250Mi
          cpu: 100m
        limits:
          memory: 1000Mi
    defaultBackend:
      enabled: false
