---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forecastle
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://stakater.github.io/stakater-charts
      chart: forecastle
      version: v1.0.63
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
      interval: 5m
  values:
    forecastle:
      image:
        name: stakater/forecastle
        tag: v1.0.63

      config:
        title: "Apps"
        namespaceSelector:
          matchNames:
            - home-automation
            - media
            - network
            - rook-ceph
            - vault
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "internal"
        hosts:
          - host: dash.komhem.xyz
            paths:
              - /
        tls:
          - hosts:
              - dash.komhem.xyz
