---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 7.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0

    image:
      repository: nodered/node-red
      tag: 1.3.1
      pullPolicy: Always

    env:
      TZ: "Europe/Stockholm"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: "https://nodered.org/about/resources/media/node-red-hexagon.svg"
        forecastle.stakater.com/network-restricted: "true"
      hosts:
        - host: node-red.komhem.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "node-red.komhem.xyz"

    persistence:
      data:
        enabled: true
        mountPath: /data
        skipuninstall: true
        existingClaim: "node-red-data"
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
        cpu: 2000m
