---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sabnzbd
      version: 7.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/sabnzbd
      tag: v3.2.1
    env:
      TZ: "Europe/Stockholm"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: "https://github.com/sabnzbd/sabnzbd/blob/develop/icons/logo-arrow.svg?raw=true"
        forecastle.stakater.com/network-restricted: "true"
      hosts:
        - host: sabnzbd.komhem.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "sabnzbd.komhem.xyz"
    persistence:
      config:
        enabled: true
        skipuninstall: true
        existingClaim: "sabnzbd-config"
    additionalVolumeMounts:
      - name: media-atlas
        mountPath: "/media"
      - name: tempdl
        mountPath: "/downloads"
    additionalVolumes:
      - name: media-atlas
        persistentVolumeClaim:
          claimName: nfs-atlas-media-pvc
      - name: tempdl
        emptyDir: {}
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 7500Mi
