---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr-uhd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 12.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:

    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1265

    env:
      TZ: "Europe/Stockholm"

    ingress:
      media:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "external"
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: "https://github.com/Sonarr/Sonarr/blob/develop/Logo/128.png?raw=true"
          forecastle.stakater.com/network-restricted: "true"
        hosts:
          - host: sonarr-uhd.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: sonarr-uhd
                  port: 8989
        tls:
          - hosts:
              - "sonarr-uhd.${SECRET_DOMAIN}"

    persistence:
      config:
        enabled: true
        skipuninstall: true
        existingClaim: "sonarr-uhd-config"
      media:
        enabled: true
        skipuninstall: true
        mountPath: "/media"
        existingClaim: nfs-atlas-media-pvc

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
        cpu: 1
