---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: rook-cephfs
