---

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: frigate-mqtt-secrets
  namespace: home-automation
spec:
  path: kvv2/mqtt-credentials
  type: Opaque
  templates:
    values.yaml: |-
      config:
        mqtt:
          user: {% .Secrets.username %}
          password: {% .Secrets.password %}
