---

apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: k8s-cluster
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
  suspend: false

---

apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: helmreleases
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      namespace: 'cert-manager'
      name: '*'
    - kind: HelmRelease
      namespace: 'development'
      name: '*'
    - kind: HelmRelease
      namespace: 'home-automation'
      name: '*'
    - kind: HelmRelease
      namespace: 'kube-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'metallb-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'monitoring'
      name: '*'
    - kind: HelmRelease
      namespace: 'vault'
      name: '*'
  suspend: false
