---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-zwavejs
  namespace: home-automation
spec:
  schedule: "30 10,22 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-zwavejs
              image: registry.komhem.xyz/docker/k8s-volume-backup:stable
              args:
                - /bin/sh
                - /backup.sh
              env:
                - name: MINIO_ACCESS_KEY
                  value: "${SECRET_MINIO_ACCESS_KEY}"
                - name: MINIO_SECRET_KEY
                  value: "${SECRET_MINIO_SECRET_KEY}"
                - name: MINIO_ENDPOINT
                  value: "192.168.20.2:9000"
                - name: MINIO_BUCKET
                  value: "backup/zwavejs"
                - name: LOCAL_PATH
                  value: "/zwave"
                - name: FILE_NAME
                  value: "zwavejs"
              volumeMounts:
                - name: zwavejs-persistent-storage
                  mountPath: /zwave
          restartPolicy: OnFailure
          volumes:
            - name: zwavejs-persistent-storage
              persistentVolumeClaim:
                claimName: zwavejs-config
