---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-code-server
  namespace: home-automation
spec:
  schedule: "5 23 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-code-server
              image: registry.komhem.xyz/docker/k8s-volume-backup:stable
              args:
                - /bin/sh
                - /backup.sh
              env:
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-credentials
                      key: MINIO_ACCESS_KEY
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-credentials
                      key: MINIO_SECRET_KEY
                - name: MINIO_ENDPOINT
                  value: "192.168.20.2:9000"
                - name: MINIO_BUCKET
                  value: "backup/code-server"
                - name: LOCAL_PATH
                  value: "/config"
                - name: FILE_NAME
                  value: "code-server"
              volumeMounts:
                - name: code-server-config
                  mountPath: /config
          restartPolicy: OnFailure
          volumes:
            - name: code-server-config
              persistentVolumeClaim:
                claimName: code-server-config
