---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nicholaswilde.github.io/helm-charts/
      chart: code-server
      version: 0.2.3
      sourceRef:
        kind: HelmRepository
        name: nicholaswilde-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0

    image:
      repository: ghcr.io/linuxserver/code-server
      # Overrides the image tag whose default is the chart appVersion.
      tag: "version-v3.10.2"

    env:
      TZ: "Europe/Stockholm"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: "https://user-images.githubusercontent.com/674621/71187801-14e60a80-2280-11ea-94c9-e56576f76baf.png"
        forecastle.stakater.com/network-restricted: "true"
      hosts:
        - host: code.komhem.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "code.komhem.xyz"

    persistence:
      config:
        enabled: true
        skipuninstall: true
        existingClaim: "code-server-config"
        mountPath: /config

    additionalVolumeMounts:
      - name: home-assistant-pvc
        mountPath: "/hass"
    additionalVolumes:
      - name: home-assistant-pvc
        persistentVolumeClaim:
          claimName: home-assistant-config

    resources:
      requests:
        cpu: 1
        memory: 1024Mi
      limits:
        cpu: 1
        memory: 2500Mi
