---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server
  namespace: home-automation
  annotations:
    kubernetes.io/ingress.class: "internal"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  labels:
    app.kubernetes.io/instance: code-server
    app.kubernetes.io/name: code-server
spec:
  rules:
    - host: "code.komhem.xyz"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: code-server
                port:
                  number: 8080
  tls:
    - hosts:
        - "code.komhem.xyz"
