---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: network
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: rook-cephfs
