---

apiVersion: batch/v1
kind: Job
metadata:
  name: restore-home-assistant
  namespace: home-automation
spec:
  template:
    spec:
      containers:
        - name: restore-home-assistant
          image: registry.komhem.xyz/docker/k8s-volume-backup:stable
          imagePullPolicy: Always
          args:
            - /bin/sh
            - /restore.sh
          env:
            - name: RESTORE_FILE
              # Update the following value with the filename of the backup you want to restore
              value: "**REPLACE_ME**"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_SECRET_KEY
            - name: MINIO_ENDPOINT
              value: "192.168.20.2:9000"
            - name: MINIO_BUCKET
              value: "backup/home-assistant"
            - name: LOCAL_PATH
              value: "/hass"
          volumeMounts:
            - name: hass-persistent-storage
              mountPath: /hass
      volumes:
        - name: hass-persistent-storage
          persistentVolumeClaim:
            claimName: home-assistant-config
      restartPolicy: Never
  backoffLimit: 4
