---

apiVersion: batch/v1
kind: Job
metadata:
  name: restore-sonarr-uhd
  namespace: media
spec:
  template:
    spec:
      containers:
        - name: restore-sonarr-uhd
          image: registry.komhem.xyz/docker/k8s-volume-backup:stable
          imagePullPolicy: Always
          args:
            - /bin/sh
            - /restore.sh
          env:
            - name: RESTORE_FILE
              # Update the following value with the filename of the backup you want to restore
              value: "**REPLACE_ME**"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_SECRET_KEY
            - name: MINIO_ENDPOINT
              value: "192.168.20.2:9000"
            - name: MINIO_BUCKET
              value: "backup/sonarr-uhd"
            - name: LOCAL_PATH
              value: "/config"
          volumeMounts:
            - name: sonarr-uhd-storage
              mountPath: /config
      volumes:
        - name: sonarr-uhd-storage
          persistentVolumeClaim:
            claimName: sonarr-uhd-config
      restartPolicy: Never
  backoffLimit: 4
