---

apiVersion: batch/v1
kind: Job
metadata:
  name: restore-zigbee2mqtt
  namespace: home-automation
spec:
  template:
    spec:
      containers:
        - name: restore-zigbee2mqtt
          image: registry.komhem.xyz/docker/k8s-volume-backup:stable
          imagePullPolicy: Always
          args:
            - /bin/sh
            - /restore.sh
          env:
            - name: RESTORE_FILE
              # Update the following value with the filename of the backup you want to restore
              value: ""
            - name: MINIO_ACCESS_KEY
              value: ""
            - name: MINIO_SECRET_KEY
              value: ""
            - name: MINIO_ENDPOINT
              value: "192.168.20.2:9000"
            - name: MINIO_BUCKET
              value: "backup/zigbee2mqtt"
            - name: LOCAL_PATH
              value: "/zigbee"
          volumeMounts:
            - name: zigbee2mqtt-persistent-storage
              mountPath: /zigbee
      volumes:
        - name: zigbee2mqtt-persistent-storage
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
      restartPolicy: Never
  backoffLimit: 4
