---

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: action-runner-k8s-cluster
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      image: summerwind/actions-runner-dind:v2.277.1
      dockerdWithinRunnerContainer: true
      repository: ahinko/k8s-cluster
      env: []

      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "0.5"
          memory: "0.5Gi"

      # Valid if dockerdWithinRunnerContainer is not true
      dockerdContainerResources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "0.5"
          memory: "1Gi"
