apiVersion: v1
kind: Secret
metadata:
    name: docker-registry-credentials
    namespace: actions-runner-system
stringData:
    registry_password: ENC[AES256_GCM,data:/axd8laoDQBbozkRVatm8y29PQ==,iv:LEv0rvKmMMLL4t+W8YO8PxjJdWGVSw/XDIq2BpTZFmE=,tag:ouUmgAoPtof24MjVhV6tRg==,type:str]
    registry_username: ENC[AES256_GCM,data:/97oUM/7r23J2v8=,iv:C2VivA/+kkSCVFpvgO8KnxUDUXUH+/itZ99/jZ3qk0I=,tag:yk+W6Nxvj6BUQ0KNmMp/WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-16T18:32:42Z"
    mac: ENC[AES256_GCM,data:jLEw+9Zg+ZsMOHuNIgJdKAKT3LWnsrUWWKNCE+9CxDgizkB6d3m3bo1V3QXxJTx4jChXROK7svZVeKDJM5Cin6XqZev22zpLDtSEwLSoIksDXNO1TZC8OCwbsZ7zfIR5fq+fqHDOmMtexzTR4SBQTYgFNIRJZbm38mH3jcMq/NE=,iv:qHwR8ux4o7Xfvi0jq+PLZ3Tk5RGsGkYDjWdqwRGatRU=,tag:SQgupvcfRogiRFnDp5Vwfg==,type:str]
    pgp:
        - created_at: "2021-06-16T18:32:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwwj9WVziM+5ARAAgDdXghh4C/d0PAWUx5Lrz62oHKhzfpKCRM+3sAWX76TH
            KQcYMhYDGMPkiXHJWNscd8ZYlzsFyBthX/2RutnsbgLtQWimsIHEX4FMu+UUKM8C
            6W4AKulC3kDENtcqXY1RuCtSLhqEK6jN4e2PuVLhV43W3xwbGtIWMqYBs4najY40
            s02f49bcoBb+uNvPfBiUjPgvO1xUw+PrIqRREmpAC1tGQUPC23dQKTB6/yAESjMw
            1qYl8JHwGEWT7TDjGAhMwsMgwfqXYrkdD2+LgST4ED0S5jqSki+LzoWOJpAaz4to
            6s9fXeK+eS+Y1s67DIbzFD2imZ/IIZiVOJ6MaLvz1sOyJYDxogsfxoUMh0p5w4Rj
            ha2nokWK3HGtPM74WxY09gBGoF1ogVJy2BUMaLPoiB2abWmkBH+VNaPVk1oQ3pQZ
            2yXJUpVUjNkAfPExHzdnwej5yRtZwHMLtD639FkjIt3J+774o60TQsZA1P/VzFkn
            EDssgVq5csCvMY8kovBi2UADAlhnrqtydzOOsnpiMWy5o6Oa+Y51Ra5HO1WhkqWf
            VmrHTBXLPwXt45c5hV8RL9+1MT997z2TFGY6NqdR03oEatqpuweAfK2M5F7crxC1
            iVuHRR4n8t4v3uGNGPRTm4IzknChqqodRDBJlWe4eXBjZDft/pP5/eolyH9MdT3S
            XgHLRvY27hv1LjygB6ua95bVpTswaqaRCLZbXlQfFHuuNf5fa7QcWjmbwTF433lo
            RcigDLWKRGhOJpaOjKjn+GNOIUi8Hw7S9roGdzAmXaZRuTB57Ai1HPHDo+pEDoo=
            =xVHp
            -----END PGP MESSAGE-----
          fp: 4F8ADC548A0D7924D2F97C4BA49FDC84B6AD510B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
