---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: jobs
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudflare-ddns
              image: registry.komhem.xyz/docker/cloudflare-ddns:stable
              env:
                - name: ZONE_ID
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare
                      key: zone_id
                - name: AUTH_KEY
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare
                      key: auth_key
                - name: RECORD_ID
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare
                      key: record_id
                - name: NAME
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare
                      key: name
                - name: WILD_RECORD_ID
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare
                      key: wild_record_id
                - name: WILD_NAME
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare
                      key: wild_name
          restartPolicy: Never
