---

#
# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#agent-worker-configuration
#

# Define the host as a control plane node
k3s_control_node: false

k3s_server:
  node-external-ip: "{{ ansible_host }}"
  node-ip: "{{ ansible_host }}"
