---

- include: registry.yaml
  when: mirror_registry is defined
        or (private_registries is defined
          and private_registries|length > 0)
  tags:
    - registry

- name: Ensure nfs-common is installed
  apt:
    name: nfs-common
    state: present
    update_cache: true
    cache_valid_time: 3600
