---

- name: Ensure /etc/rancher/k3s exists
  become: true
  file:
    path: "/etc/rancher/k3s"
    state: directory
    mode: 0644

- name: Ensure registry configuration is set
  become: true
  template:
    src: "registries.yaml.j2"
    dest: "/etc/rancher/k3s/registries.yaml"
    mode: 0644

- name: Ensure k3s service is restarted
  systemd:
    name: k3s.service
    daemon_reload: yes
    enabled: yes
    state: restarted
