---

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: botkube-helm-values
  namespace: monitoring
spec:
  path: kvv2/botkube-config
  type: Opaque
  templates:
    values.yaml: |-
      communications:
        slack:
          enabled: true
          channel: {% .Secrets.slack_channel %}
          token: {% .Secrets.slack_api_token %}
