---

- hosts:
    - control-nodes
  gather_facts: true
  vars_prompt:
    - name: "run_confirmation"
      prompt: "Are you sure you want to run this over the control plane nodes? [Y/n]"
      default: "n"
      private: false
  any_errors_fatal: false
  pre_tasks:
    - name: check confirmation
      fail:
        msg: "Abort."
      when: run_confirmation != "Y"
  roles:
    - {role: keepalived}
    - {role: haproxy}
    - {role: dnscrypt-proxy}
  tasks:
    - name: Ensure nfs-common is installed
      apt:
        name: nfs-common
        state: present
        update_cache: true
        cache_valid_time: 3600
