---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwave2mqtt
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zwave2mqtt
      version: 7.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: robertslando/zwave2mqtt
      tag: 4.1.1

    replicaCount: 1
    strategy:
      type: Recreate

    env:
      TZ: "Europe/Stockholm"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
        - host: zwave.komhem.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "zwave.komhem.xyz"

    securityContext:
      privileged: true

    persistence:
      config:
        enabled: true
        mountPath: /usr/src/app/store
        skipuninstall: true
        existingClaim: "zwave2mqtt-config"

    # Path to your zwave device in the container
    additionalVolumeMounts:
      - name: usb
        mountPath: /dev/serial/by-id/usb-0658_0200-if00

    # Path to your zwave device on the host
    additionalVolumes:
      - name: usb
        hostPath:
          path: /dev/serial/by-id/usb-0658_0200-if00

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - {key: "feature.node.kubernetes.io/custom-zwave", operator: In, values: ["true"]}

    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
