---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave2mqtt-config
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
