---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-sonarr
  namespace: media
spec:
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-sonarr
              image: registry.komhem.xyz/docker/k8s-volume-backup:stable
              args:
                - /bin/sh
                - /backup.sh
              env:
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-credentials
                      key: MINIO_ACCESS_KEY
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-credentials
                      key: MINIO_SECRET_KEY
                - name: MINIO_ENDPOINT
                  value: "192.168.20.2:9000"
                - name: MINIO_BUCKET
                  value: "backup/sonarr"
                - name: LOCAL_PATH
                  value: "/sonarr"
                - name: FILE_NAME
                  value: "sonarr"
              volumeMounts:
                - name: sonarr-persistent-storage
                  mountPath: /sonarr
          restartPolicy: OnFailure
          volumes:
            - name: sonarr-persistent-storage
              persistentVolumeClaim:
                claimName: sonarr-config
