---

version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:v5.7
    restart: always
    environment:
      - TZ=Europe/Stockholm
      - WEBPASSWORD=${ADMIN_PASSWORD}
      - DNS1=192.168.20.6
      - DNS2=192.168.20.7
    dns:
      - 1.1.1.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 5380:80
    cap_add:
      - NET_ADMIN
