---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-bazarr
  namespace: media
spec:
  schedule: "20 12 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-bazarr
              image: registry.komhem.xyz/docker/k8s-volume-backup:stable
              args:
                - /bin/sh
                - /backup.sh
              env:
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-credentials
                      key: MINIO_ACCESS_KEY
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-credentials
                      key: MINIO_SECRET_KEY
                - name: MINIO_ENDPOINT
                  value: "192.168.20.2:9000"
                - name: MINIO_BUCKET
                  value: "backup/bazarr"
                - name: LOCAL_PATH
                  value: "/bazarr"
                - name: FILE_NAME
                  value: "bazarr"
              volumeMounts:
                - name: bazarr-persistent-storage
                  mountPath: /bazarr
          restartPolicy: OnFailure
          volumes:
            - name: bazarr-persistent-storage
              persistentVolumeClaim:
                claimName: bazarr-config
