---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bazarr
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v0.9.1.1
    env:
      TZ: "Europe/Stockholm"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
        - host: bazarr.komhem.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "bazarr.komhem.xyz"
    persistence:
      config:
        enabled: true
        skipuninstall: true
        existingClaim: "bazarr-config"
    additionalVolumeMounts:
      - name: media-atlas
        mountPath: "/media"
    additionalVolumes:
      - name: media-atlas
        persistentVolumeClaim:
          claimName: nfs-atlas-media-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
