---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-sabnzbd
  namespace: media
spec:
  schedule: "25 12 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-sabnzbd
              image: registry.${SECRET_DOMAIN}/docker/k8s-volume-backup:stable
              args:
                - /bin/sh
                - /backup.sh
              env:
                - name: MINIO_ACCESS_KEY
                  value: "${SECRET_MINIO_ACCESS_KEY}"
                - name: MINIO_SECRET_KEY
                  value: "${SECRET_MINIO_SECRET_KEY}"
                - name: MINIO_ENDPOINT
                  value: "192.168.20.2:9000"
                - name: MINIO_BUCKET
                  value: "backup/sabnzbd"
                - name: LOCAL_PATH
                  value: "/sabnzbd"
                - name: FILE_NAME
                  value: "sabnzbd"
              volumeMounts:
                - name: sabnzbd-persistent-storage
                  mountPath: /sabnzbd
          restartPolicy: OnFailure
          volumes:
            - name: sabnzbd-persistent-storage
              persistentVolumeClaim:
                claimName: sabnzbd-config
