---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sabnzbd
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/sabnzbd
      tag: v3.3.1
    env:
      TZ: "Europe/Stockholm"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "external"
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: "https://github.com/sabnzbd/sabnzbd/blob/develop/icons/logo-arrow.svg?raw=true"
          forecastle.stakater.com/network-restricted: "true"
        hosts:
          - host: sabnzbd.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sabnzbd.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        skipuninstall: true
        existingClaim: "sabnzbd-config"

      tempdl:
        enabled: true
        type: emptyDir
        mountPath: /downloads

      media:
        enabled: true
        skipuninstall: true
        existingClaim: "nfs-atlas-media-pvc"

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 7500Mi
