---

# Configure a registry mirror, useful for having a pull-through cache
# mirror_registry:
  # address: "registry-cache.komhem.xyz"

# Configure private registries
private_registries:
- address: "registry.komhem.xyz"
  username: "admin"
  password: "password"
