---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consul
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: consul
      version: 0.31.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp-charts
        namespace: flux-system
      interval: 5m
  values:
    global:
      image: "hashicorp/consul:1.9.6"
    server:
      enabled: true
      storage: "10Gi"
      storageClass: rook-cephfs
