---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-sonarr-uhd
  namespace: media
spec:
  schedule: "10 12 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-sonarr-uhd
              image: registry.komhem.xyz/docker/k8s-volume-backup:stable
              args:
                - /bin/sh
                - /backup.sh
              env:
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-credentials
                      key: MINIO_ACCESS_KEY
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-credentials
                      key: MINIO_SECRET_KEY
                - name: MINIO_ENDPOINT
                  value: "192.168.20.2:9000"
                - name: MINIO_BUCKET
                  value: "backup/sonarr-uhd"
                - name: LOCAL_PATH
                  value: "/sonarr-uhd"
                - name: FILE_NAME
                  value: "sonarr-uhd"
              volumeMounts:
                - name: sonarr-uhd-persistent-storage
                  mountPath: /sonarr-uhd
          restartPolicy: OnFailure
          volumes:
            - name: sonarr-uhd-persistent-storage
              persistentVolumeClaim:
                claimName: sonarr-uhd-config
