---

version: '3.8'

services:
  timemachine:
    container_name: timemachine
    image: mbentley/timemachine:smb
    restart: always
    environment:
      - EXTERNAL_CONF=/etc/timemachine/conf
    volumes:
      - /tank/backup/tm:/opt
      - /tank/kubernetes/volumes/timemachine/conf:/etc/timemachine/conf
      - /tank/kubernetes/volumes/timemachine/var/lib/samba:/var/lib/samba
      - /tank/kubernetes/volumes/timemachine/var/cache/samba:/var/cache/samba
      - /tank/kubernetes/volumes/timemachine/run/samba:/run/samba
    network_mode: "host"
