---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 2.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.10

    podAnnotations:
      secret.reloader.stakater.com/reload: "mosquitto-users-config"

    replicaCount: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0

    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

    persistence:
      data:
        enabled: true
        storageClass: "rook-cephfs"
        accessMode: ReadWriteMany
        size: 1Gi

    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.20.220
