---

- name: Ensure keepalived is installed
  apt:
    name: keepalived, libipset-dev
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Ensure keepalived conf is set
  template:
    mode: 0644
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Add user
  ansible.builtin.user:
    name: keepalived_script
    comment: Keepalived
    group: users
    create_home: false

- name: Ensure keepalived is started
  service:
    name: keepalived
    state: started
    enabled: true
