---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-atlas-pv
spec:
  storageClassName: nfs-client-atlas
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.20.2
    path: /
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
