---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-node-feature-discovery-charts
        namespace: flux-system
      interval: 5m
  values:
    podAnnotations:
      configmap.reloader.stakater.com/reload: "nfd-worker-conf"
    image:
      repository: k8s.gcr.io/nfd/node-feature-discovery
      tag: v0.8.0

    worker:
      config: |-
        core:
          sources:
            - custom
            - pci
            - usb

        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - "class"
              - "vendor"
              - "device"
          custom:
            - name: "zwave"
              matchOn:
                - usbId:
                    class: ["02"]
                    vendor: ["0658"]
                    device: ["0200"]
            - name: "intel-gpu"
              matchOn:
                - pciId:
                    class: ["0300"]
                    vendor: ["8086"]
            - name: "coral-tpu"
              matchOn:
                - usbId:
                    vendor: ["1a6e", "18d1"]
            - name: "zigbee"
              matchOn:
                - usbId:
                    class: ["02"]
                    vendor: ["0451"]
                    device: ["16a8"]
