---

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: frigate-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://blakeblackshear.github.io/blakeshome-charts/
  timeout: 3m
