---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: network
spec:
  schedule: "*/20 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 10
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cloudflare-ddns
              image: curlimages/curl:7.77.0
              envFrom:
                - secretRef:
                    name: cloudflare-ddns
              command:
                - "/bin/sh"
                - "-ec"
                - |
                  set -o nounset
                  set -o errexit

                  IP=$(curl -s ifconfig.co)

                  CURRENT_RECORD=$(curl -s -X GET \
                    "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records?name=$CLOUDFLARE_DOMAIN_NAME&type=A" \
                        -H "Authorization: Bearer $CLOUDFLARE_AUTH_KEY" \
                        -H "Content-Type: application/json" \
                  )

                  CURRENT_IP=$(echo "$CURRENT_RECORD" | sed -n 's/.*"content":"\([^"]*\).*/\1/p')
                  if [ "$IP" = "$CURRENT_IP" ]; then
                    printf "%s - Success - IP Address '%s' has not changed" "$(date -u)" "$IP"
                    exit 0
                  fi

                  UPDATE=$(curl -X PUT "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records/$CLOUDFLARE_RECORD_ID" \
                      -H "Authorization: Bearer $CLOUDFLARE_AUTH_KEY" \
                      -H "Content-Type: application/json" \
                      --data "{\"type\":\"A\",\"name\":\"*.$CLOUDFLARE_DOMAIN_NAME\",\"content\":\"$IP\"}")

                  if echo "$UPDATE" | grep -q '\"success\":false'; then
                    printf "%s - Yikes - Updating IP Address '%s' has failed" "$(date -u)" "$IP"
                    exit 1
                  else
                    printf "%s - Success - IP Address '%s' has been updated" "$(date -u)" "$IP"
                    exit 0
                  fi
