---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://infracloudio.github.io/charts
      chart: botkube
      version: v0.12.1
      sourceRef:
        kind: HelmRepository
        name: infracloudio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: infracloudio/botkube
      tag: v0.12.1
      pullPolicy: IfNotPresent
    podAnnotations:
      secret.reloader.stakater.com/reload: "botkube-config"
    # serviceMonitor:
    # enabled: true
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

    communications:
      slack:
        enabled: true
        channel: "${SECRET_BOTKUBE_SLACK_CHANNEL}"
        token: "${SECRET_BOTKUBE_SLACK_TOKEN}"

    config:
      settings:
        clustername: k8s
        kubectl:
          # Set true to enable kubectl commands execution
          enabled: false
      recommendations: false
      resources:
        - name: v1/pods
          namespaces:
            include:
              - default
              - flux-system
              - home-automation
              - kube-system
              - media
              - metallb-system
              - monitoring
              - system-upgrade
              - tigera-operator
          events:
            - create
            - error
            - delete
        - name: v1/pods
          namespaces:
            include:
              - rook-ceph
              - cert-manager
              - network
          events:
            - error
        - name: v1/services
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: apps/v1/deployments
          namespaces:
            include:
              - all
          events:
            - create
            - update
            - delete
            - error
        - name: apps/v1/statefulsets
          namespaces:
            include:
              - all
          events:
            - create
            - update
            - delete
            - error
        - name: networking.k8s.io/v1beta1/ingresses
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/nodes
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/namespaces
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumes
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumeclaims
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/configmaps
          namespaces:
            include:
              - default
              - flux-system
              - home-automation
              - kube-system
              - media
              - metallb-system
              - monitoring
              - network
              - system-upgrade
              - tigera-operator
          events:
            - create
            - error
            - delete
        - name: v1/configmaps
          namespaces:
            include:
              - rook-ceph
          events:
            - error
        - name: apps/v1/daemonsets
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: batch/v1/jobs
          namespaces:
            include:
              - all
          events:
            - update
            - error
        - name: rbac.authorization.k8s.io/v1/rolebindings
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/clusterrolebindings
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/clusterroles
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
