---

name: flux-update-schedule

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */6 * * *"

jobs:
  flux-update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Upgrade Flux components
        id: upgrade
        run: |
          UGLY_VERSION="$(flux -v)"
          VERSION="v${UGLY_VERSION#*flux version }"
          flux install --version="${VERSION}" \
            --network-policy=false \
            --export > ./cluster/bootstrap/flux-system/gotk-components.yaml
          echo "::set-output name=flux_version::$VERSION"

      - name: Remove untracked files
        run: |
          sudo git clean -f -d

      - name: Create pull request for Flux update
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "flux/upgrade-${{ steps.update.outputs.flux_version }}"
          delete-branch: true
          title: "chore(deps): upgrade flux components to ${{ steps.upgrade.outputs.flux_version }}"
          signoff: true
          committer: "Peter Ahinko <ahinkop@users.noreply.github.com>"
          author: "Peter Ahinko <ahinko@users.noreply.github.com>"
          assignees: "ahinko"
          commit-message: "chore(deps): upgrade flux components to ${{ steps.upgrade.outputs.flux_version }}"
          body: |
            Release notes: https://github.com/fluxcd/flux2/releases/tag/${{ steps.upgrade.outputs.flux_version }}
          labels: flux/update
