name: lint

on:
  push:
    branches:
      - main

jobs:
  lint-yaml:
    runs-on:
      - self-hosted
    if: "!contains(github.event.head_commit.message, '[ci-skip]') || github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install yamllint
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip
          sudo pip3 install yamllint

      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: "./cluster"
          config_file: "./.github/yamllint.config.yaml"

  lint-shell:
    runs-on:
      - self-hosted
    if: "!contains(github.event.head_commit.message, '[ci-skip]') || github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Lint shell scripts
        uses: reviewdog/action-shellcheck@v1
        with:
          path: "./tools"
          level: "error"

  lint-ansible:
    runs-on:
      - self-hosted
    if: "!contains(github.event.head_commit.message, '[ci-skip]') || github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Lint ansible
        uses: ansible/ansible-lint-action@master
        with:
          targets: "ansible/"
          args: "-c .github/ansible-lint.yaml"
