---

- hosts: "{{ update_host | default('update_host') }}"
  gather_facts: true
  any_errors_fatal: true

  vars_prompt:
    - name: "run_confirmation"
      prompt: "Are you sure you want to update node ? [Y/n]"
      default: "n"
      private: false

  pre_tasks:
    - name: check confirmation
      fail:
        msg: "Abort."
      when: run_confirmation != "Y"

  tasks:
    - name: upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        cache_valid_time: 3600
        autoclean: true
        autoremove: true
      register: apt_upgrade
      retries: 5
      until: apt_upgrade is success
